In [9]:
import numpy as np



In [13]:
np.array()

3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(3d)


SyntaxError: invalid syntax (<ipython-input-13-186108c54395>, line 3)

# 3 ans

In [15]:
import pprint
n = 3
distance = [[[0 for k in range(n)] for j in range(n)] for i in range(n)] 
pprint.pprint(distance)

[[[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]


# 4 ans

In [51]:
import numpy as np
np.random.rand(5)
np.random.rand(4,4)


array([[0.69842864, 0.84667974, 0.1020254 , 0.36149159],
       [0.19382265, 0.39355052, 0.57558779, 0.6962535 ],
       [0.56351593, 0.16854769, 0.49755033, 0.66898071],
       [0.05643431, 0.94674764, 0.24425833, 0.72630662]])

# 15 ans

In [23]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['@#$','#$%','#%e','&*'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, '@#$', 12.2)
(2, '#$%', 15.)
(3, '#%e', 20.)


# 14 ans

In [36]:
arr =[1,3,6,9]
max = arr[0]
n=len(arr)
for i in range (0,n):
    if arr[i]>max:
        max=arr[i]
print(max)

9


# 9 ans

In [43]:
import numpy as np

x = np.full((6, 4),76)
print(x)

[[76 76 76 76]
 [76 76 76 76]
 [76 76 76 76]
 [76 76 76 76]
 [76 76 76 76]
 [76 76 76 76]]


# 7 ans

In [46]:
arr1 = [3, 5, 2, 5, 2]; 
arr2 = [2, 3, 5, 5, 2]; 
n = len(arr1); 
m = len(arr2); 
  
if (areEqual(arr1, arr2, n, m)): 
    print("Yes"); 
else: 
    print("No")

Yes


# 5 ans

In [48]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Common values between two arrays:
[10 40]


# 6 ans

In [50]:
import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-07-26
Today :  2020-07-27
Tomorrow :  2020-07-28


# 3 ans

In [52]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
